name: Playtime For The Buck
markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'ptb_frontend.gemspec']
assets:
  js_compressor:  uglifier
  css_compressor: sass
  debug: false