name: Playtime For The Buck
markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'ptb_frontend.gemspec', 'Rakefile']
assets:
  js_compressor:  uglifier
  css_compressor: sass
  debug: true
  cachebust: none
  gzip: false
  cache: true