name: Playtime For The Buck
markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'generate_pre_built_tables.rb']
assets:
  js_compressor:  uglifier
  css_compressor: sass
  debug: false