
### Root route #####
####################
"/":
  sort: playtimeOverBuck
  title: "It ended up being a little more than playtime for the buck: it kind of let you discover games&trade;"

### OS Routes ######
####################
# linux:
#   os: linux
# osx:
#   os: osx
# windows:
#   os: windows

### Launch date ####
####################
recently-launched:
  title: List of recently launched games
  sort: launchDate 
  launchDate: '+0d~'
oldest-games:
  title: The oldest games of Steam
  sortd: launchDate
old-games:
  title: Games older than 5 years
  sortLaunchDate:
  launchDate: 5y~

### Price ##########
####################
lowest-price:
  title: Non-free games with the lowest prices
  sort: finalPrice
  finalPrice: '>0~'
most-expensive:
  title: The most expensive games
  sortd: finalPrice
free:
  title: Free games
  finalPrice: '~0'
# sale:
#   sale: yes

### Game tags ######
####################
strategy:
  title: Strategy games
  sort: tags
  tags: strategy
fps:
  title: "FPS [First Person Shooter] games"
  sort: tags
  tags: fps
action:
  title: Action games
  sort: tags
  tags: action
adventure:
  title: Adventure games
  sort: tags
  tags: adventure
indie:
  title: Indie games
  sort: tags
  tags: indie
simulation:
  title: Simulation games
  sort: tags
  tags: simulation
co-op:
  title: Co-op games
  sort: tags
  tags: co-op
local-co-op:
  title: Local Co-op games
  sort: tags
  tags: local co-op
moba:
  title: Moba games
  sort: tags
  tags: moba
comedy:
  title: Comedy games
  sort: tags
  tags: comedy
point-and-click:
  title: "Point & click games"
  sort: tags
  tags: point and click
space:
  title: Space games
  sort: tags
  tags: space
sci-fi:
  title: Sci-fi games
  sort: tags
  tags: sci-fi
classic:
  title: Classic games
  sort: tags
  tags: classic 
retro:
  title: Retro games
  sort: tags
  tags: retro
city-builder:
  title: City building games
  sort: tags
  tags: city builder
tycoon:
  title: Tycoon games
  sort: tags
  tags: tycoon
puzzle:
  title: Puzzle games
  sort: tags
  tags: puzzle
platformer:
  title: Platformer games
  sort: tags
  tags: platformer
underrated:
  title: Underrated games
  sort: tags
  tags: underrated
tower-defense:
  title: Tower defense games
  sort: tags
  tags: tower defense
casual:
  title: F*cking casual games
  sort: tags
  tags: casual

### Reviews ########
####################
most-reviews:
  title: Games with a lot of reviews
  sortd: reviews
best-reviews:
  title: Games with the best reviews
  sortd: reviewsDistribution
  reviews: 50~
worse-reviews:
  title: Games with the worse reviews
  sort: reviewsDistribution
  reviews: 50~
good-reviews:
  title: Games with good reviews
  sortd: reviewsDistribution
  reviewsDistribution: 90
  reviews: 100~

### The rest #######
####################
low-playtime-disparity:
  title: Games with the lowest playtime disparity
  sort: playtimeDisparity
  reviews: 10~
most-playtime:
  title: Games with the highest amount of playing time
  sortd: playtime
best-metascore:
  title: Games with the best metascore
  sortd: metascore
worse-metascore:
  title: Games with the worse metascore
  sort: metascore
  metascore: 0~

# technically-underrated:
#   title: Technically underrated games
#   sortPositiveReviewsPercentage: descending
#   totalReviews: 50~200

# lowest-hardware-requirements:
#   sortHardwareRequirements: 

# highest-hardware-requirements:
#   sortHardwareRequirements: descending