"/":
  title: "It ended up being a little more than playtime for the buck: it kind of let you discover games&trade;"

# OS Routes
linux:
  os: linux
osx:
  os: osx
windows:
  os: windows

# Launch date
recently-launched:
  sortLaunchDate:
  title: List of recently launched games
  launchDate: '+0d~'
oldest-games:
  sortLaunchDate: descending
old-games:
  sortLaunchDate:
  launchDate: 5y~

# Price routes
lowest-price:
  sortFinalPrice:
  finalPrice: '>0-*'
most-expensive:
  sortFinalPrice: descending
free:
  finalPrice: '*-0'
sale:
  sale: yes

# Game tags

# "/strategy": "tags=strategy&sortTagsRating",
# "/fps": "tags=fps&sortTagsRating",
# "/action": "tags=action&sortTagsRating",
# "/adventure": "tags=adventure&sortTagsRating",
# "/indie": "tags=indie&sortTagsRating",
# "/simulation": "tags=simulation&sortTagsRating",
# "/co-op": "tags=co-op&sortTagsRating",
# "/counch-co-op": "tags=couch%20co-op&sortTagsRating",
# "/moba": "tags=moba&sortTagsRating",
# "/comedy": "tags=comedy&sortTagsRating",
# "/point-and-click": "tags=point-and-click&sortTagsRating",
# "/space": "tags=space&sortTagsRating",
# "/sci-fi": "tags=sci-fi&sortTagsRating",
# "/classic": "tags=classic&sortTagsRating",
# "/retro": "tags=retro&sortTagsRating",
# "/city-builder": "tags=city%20builder&sortTagsRating",
# "/tycoon": "tags=tycoon&sortTagsRating",
# "/puzzle": "tags=puzzle&sortTagsRating",
# "/platformer": "tags=platformer&sortTagsRating",
# "/underrated": "tags=underrated&sortTagsRating",
# "/tower-defense": "tags=tower%20defense&sortTagsRating",

# "/technically-underrated": "totalReviews=50-200&sortPositiveReviewsPercentage=descending",

# "/most-reviews": "sortTotalReviews=descending",
# "/best-reviews": "sortPositiveReviewsPercentage=descending",

# "/good-reviews": "sortPositiveReviewsPercentage=descending&positiveReviewsPercentage=90&totalReviews=100-*",
# "/low-playtime-disparity": "sortPlaytimeDeviationPercentage&totalReviews=10-*",
# "/most-playtime": "sortAverage_time=descending",
# "/best-metascore": "sortMeta_score=descending",
# "/lowest-hardware-requirements": "sortHardware_requirements_index=descending",
# "/highest-hardware-requirements": "sortHardware_requirements_index",